In [5]:
import word2vec
import numpy as np

In [6]:
arr = np.array([
    [1,2,3],
    [2,3,4]
])

cvec = [1, 2, 3]

In [8]:
np.dot(arr, cvec)

array([14, 20])

In [16]:
np.matmul(np.array([1,2,3]).reshape(3,1), np.array([1,2,3]).reshape((1, 3)))

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [14]:
np.array([1,2,3]).shape

(3,)

In [23]:
np.array([[1],[2],[3], [3], [5]]).reshape(5,) * np.array([1,2,3]).reshape(3,)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [29]:
a = np.array([1,2,3])
b = np.stack([a, a])

In [35]:
a = np.stack([a] * 5)

In [36]:
a * 3

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [42]:
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [41]:
np.transpose(np.transpose(a) * np.array([1,2,3,4,5]))

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12],
       [ 5, 10, 15]])

In [60]:
a = np.arange(11)
b = np.stack([a, a, a]).T
print(a.shape, b.shape)

(11,) (11, 3)


In [65]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
b

array([[ 0,  0,  0],
       [ 1,  1,  1],
       [ 2,  2,  2],
       [ 3,  3,  3],
       [ 4,  4,  4],
       [ 5,  5,  5],
       [ 6,  6,  6],
       [ 7,  7,  7],
       [ 8,  8,  8],
       [ 9,  9,  9],
       [10, 10, 10]])

In [63]:
b.shape

(11, 3)

In [67]:
c =(a * b.T).T
c

array([[  0,   0,   0],
       [  1,   1,   1],
       [  4,   4,   4],
       [  9,   9,   9],
       [ 16,  16,  16],
       [ 25,  25,  25],
       [ 36,  36,  36],
       [ 49,  49,  49],
       [ 64,  64,  64],
       [ 81,  81,  81],
       [100, 100, 100]])

In [57]:
np.sum(c, axis=1)

array([432, 432, 432, 432, 432, 432, 432, 432, 432, 432, 432])